# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_profile(object):
    def setupUi(self, choose_profile):
        choose_profile.setObjectName("choose_profile")
        choose_profile.resize(412, 732)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        choose_profile.setFont(font)
        self.centralwidget = QtWidgets.QWidget(choose_profile)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 640, 394, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 50, 394, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 190, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 190, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 380, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 380, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setObjectName("pushButton_4")
        choose_profile.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(choose_profile)
        self.statusbar.setObjectName("statusbar")
        choose_profile.setStatusBar(self.statusbar)

        self.retranslateUi(choose_profile)
        QtCore.QMetaObject.connectSlotsByName(choose_profile)

    def retranslateUi(self, choose_profile):
        _translate = QtCore.QCoreApplication.translate
        choose_profile.setWindowTitle(_translate("choose_profile", "MainWindow"))
        self.pushButton.setText(_translate("choose_profile", "profile1"))
        self.pushButton_2.setText(_translate("choose_profile", "profile2"))
        self.pushButton_3.setText(_translate("choose_profile", "profile3"))
        self.pushButton_4.setText(_translate("choose_profile", "profile4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    choose_profile = QtWidgets.QMainWindow()
    ui = Ui_choose_profile()
    ui.setupUi(choose_profile)
    choose_profile.show()
    sys.exit(app.exec_())
