# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirm(object):
    #Method for reject instance
    def handle_no(self, conf_v):
        conf_v.hide()  # Hide the confirmation window
        
    def handle_yes(self):
        # Deletes Json profiles
        pass

    def setupUi(self, confirmation):
        confirmation.setObjectName("confirmation")
        confirmation.resize(412, 168)
        self.warning = QtWidgets.QLabel(confirmation)
        self.warning.setGeometry(QtCore.QRect(40, 30, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.warning.setFont(font)
        self.warning.setObjectName("warning")
        self.yes = QtWidgets.QPushButton(confirmation)
        self.yes.setGeometry(QtCore.QRect(70, 90, 93, 28))
        self.yes.setObjectName("yes")
        self.no = QtWidgets.QPushButton(confirmation)
        self.no.setGeometry(QtCore.QRect(250, 90, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.no.setFont(font)
        self.no.setObjectName("no")

        # Handles no instance when clicked.
        # Lambda function is used to create a callable function that takes no arguments and calls the handle_no method with the confirmation.
        self.no.clicked.connect(lambda: self.handle_no(confirmation))

        self.retranslateUi(confirmation)
        QtCore.QMetaObject.connectSlotsByName(confirmation)

    def retranslateUi(self, confirmation):
        _translate = QtCore.QCoreApplication.translate
        confirmation.setWindowTitle(_translate("confirmation", "confirmation"))
        self.warning.setText(_translate("confirmation", "Are you sure you want to delete all data?"))
        self.yes.setText(_translate("confirmation", "Yes!"))
        self.no.setText(_translate("confirmation", "NO!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirmation = QtWidgets.QDialog()
    ui = Ui_confirm()
    ui.setupUi(confirmation)
    confirmation.show()
    sys.exit(app.exec_())
