# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'difficulty_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_difficulty_choose(object):
    def setupUi(self, difficulty_choose):
        difficulty_choose.setObjectName("difficulty_choose")
        difficulty_choose.resize(412, 732)
        self.centralwidget = QtWidgets.QWidget(difficulty_choose)
        self.centralwidget.setObjectName("centralwidget")
        self.easy_button = QtWidgets.QPushButton(self.centralwidget)
        self.easy_button.setGeometry(QtCore.QRect(80, 140, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.easy_button.setFont(font)
        self.easy_button.setIconSize(QtCore.QSize(16, 16))
        self.easy_button.setAutoRepeatDelay(300)
        self.easy_button.setObjectName("easy_button")
        self.intermediate_button = QtWidgets.QPushButton(self.centralwidget)
        self.intermediate_button.setGeometry(QtCore.QRect(80, 310, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.intermediate_button.setFont(font)
        self.intermediate_button.setIconSize(QtCore.QSize(16, 16))
        self.intermediate_button.setAutoRepeatDelay(300)
        self.intermediate_button.setObjectName("intermediate_button")
        self.advanced_button = QtWidgets.QPushButton(self.centralwidget)
        self.advanced_button.setGeometry(QtCore.QRect(80, 480, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.advanced_button.setFont(font)
        self.advanced_button.setIconSize(QtCore.QSize(16, 16))
        self.advanced_button.setAutoRepeatDelay(300)
        self.advanced_button.setObjectName("advanced_button")
        difficulty_choose.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(difficulty_choose)
        self.statusbar.setObjectName("statusbar")
        difficulty_choose.setStatusBar(self.statusbar)

        self.retranslateUi(difficulty_choose)
        QtCore.QMetaObject.connectSlotsByName(difficulty_choose)

    def retranslateUi(self, difficulty_choose):
        _translate = QtCore.QCoreApplication.translate
        difficulty_choose.setWindowTitle(_translate("difficulty_choose", "Choose Difficulty"))
        self.easy_button.setText(_translate("difficulty_choose", "Beginner"))
        self.intermediate_button.setText(_translate("difficulty_choose", "Intermediate"))
        self.advanced_button.setText(_translate("difficulty_choose", "Advanced"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    difficulty_choose = QtWidgets.QMainWindow()
    ui = Ui_difficulty_choose()
    ui.setupUi(difficulty_choose)
    difficulty_choose.show()
    sys.exit(app.exec_())
