# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from view_routine import Ui_view_routine
from defaults import *

#Screen will not open unless choose a difficulty first
class Ui_program_choose(object):
    def setupUi(self, program_choose, difficulty):
        #Stores the difficulty level from program_choose.py!

        '''
        The line self.difficulty = difficulty stores the selected difficulty value in 
        the Ui_program_choose class's self.difficulty attribute from program_choose.py
        The difficulty value is now accessible in the program_choose.py module.
        '''
        self.difficulty = difficulty

        #I found out that it's easier to close window by parsing it
        self.win = program_choose

        program_choose.setObjectName("program_choose")
        program_choose.resize(WIDTH, HEIGHT)
        program_choose.setFixedWidth(WIDTH)
        program_choose.setFixedHeight(HEIGHT)
        program_choose.setMaximumWidth(WIDTH)
        program_choose.setMaximumHeight(HEIGHT)

        self.centralwidget = QtWidgets.QWidget(program_choose)
        self.centralwidget.setObjectName("centralwidget")
        self.arms_button = QtWidgets.QPushButton(self.centralwidget)
        self.arms_button.setGeometry(QtCore.QRect(80, 80, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.arms_button.setFont(font)
        self.arms_button.setIconSize(QtCore.QSize(16, 16))
        self.arms_button.setAutoRepeatDelay(300)
        self.arms_button.setObjectName("arms_button")
        self.arms_button.setStyleSheet("background-color: {};".format(BUTTON_COLOR2))

        self.arms_button.clicked.connect(lambda:self.program("arms"))

        self.legs_button = QtWidgets.QPushButton(self.centralwidget)
        self.legs_button.setGeometry(QtCore.QRect(80, 240, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.legs_button.setFont(font)
        self.legs_button.setIconSize(QtCore.QSize(16, 16))
        self.legs_button.setAutoRepeatDelay(300)
        self.legs_button.setObjectName("legs_button")
        self.legs_button.setStyleSheet("background-color: {};".format(BUTTON_COLOR1))

        self.legs_button.clicked.connect(lambda:self.program("legs"))

        self.core_button = QtWidgets.QPushButton(self.centralwidget)
        self.core_button.setGeometry(QtCore.QRect(80, 400, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.core_button.setFont(font)
        self.core_button.setIconSize(QtCore.QSize(16, 16))
        self.core_button.setAutoRepeatDelay(300)
        self.core_button.setObjectName("core_button")
        self.core_button.setStyleSheet("background-color: {};".format(BUTTON_COLOR4))

        self.core_button.clicked.connect(lambda:self.program("core"))

        self.cardio_button = QtWidgets.QPushButton(self.centralwidget)
        self.cardio_button.setGeometry(QtCore.QRect(80, 560, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.cardio_button.setFont(font)
        self.cardio_button.setIconSize(QtCore.QSize(16, 16))
        self.cardio_button.setAutoRepeatDelay(300)
        self.cardio_button.setObjectName("cardio_button")
        self.cardio_button.setStyleSheet("background-color: {};".format(BUTTON_COLOR3))

        self.cardio_button.clicked.connect(lambda:self.program("cardio"))

        program_choose.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(program_choose)
        self.statusbar.setObjectName("statusbar")
        program_choose.setStatusBar(self.statusbar)

        program_choose.setStyleSheet("background-color: {};".format(THEME_COLOR))

        self.retranslateUi(program_choose)
        QtCore.QMetaObject.connectSlotsByName(program_choose)

    def retranslateUi(self, program_choose):
        _translate = QtCore.QCoreApplication.translate
        program_choose.setWindowTitle(_translate("program_choose", "Choose a Program"))
        self.arms_button.setText(_translate("program_choose", "Arms"))
        self.legs_button.setText(_translate("program_choose", "Legs"))
        self.core_button.setText(_translate("program_choose", "Core"))
        self.cardio_button.setText(_translate("program_choose", "Cardio"))

    def program(self, program):
        self.program = program
        print(self.difficulty, program)  #Print the difficulty and program
        
        #Opens view_routine.py
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_view_routine()
        self.ui.setupUi(self.window, self.program, self.difficulty)
        self.window.show()
        
        #Closes window of program_choose.py
        self.win.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    program_choose = QtWidgets.QMainWindow()
    ui = Ui_program_choose()
    ui.setupUi(program_choose)
    program_choose.show()
    sys.exit(app.exec_())
