# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from confirmation import Ui_confirm
import json

#Settings class for defaults modification and profile deletions.
#Named ui_settings_2 because it's a duplicate of an old class that I didn't delete in bin
class Ui_settings_2(object):

    #Initialize UI.
    def setupUi(self, settings_2):
        settings_2.setObjectName("settings_2")
        settings_2.resize(412, 732)
        self.centralwidget = QtWidgets.QWidget(settings_2)
        self.centralwidget.setObjectName("centralwidget")
        self.theme_chager = QtWidgets.QPushButton(self.centralwidget)
        self.theme_chager.setEnabled(True)
        self.theme_chager.setGeometry(QtCore.QRect(60, 140, 301, 91))
        self.theme_chager.setObjectName("theme_chager")

        #When CLicked, changes the theme of the applciation.
        self.theme_chager.clicked.connect(self.edit_theme)

        self.settings = QtWidgets.QLabel(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(120, 40, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.settings.setFont(font)
        self.settings.setObjectName("settings")
        self.delete_data = QtWidgets.QPushButton(self.centralwidget)
        self.delete_data.setEnabled(True)
        self.delete_data.setGeometry(QtCore.QRect(60, 270, 301, 91))
        self.delete_data.setObjectName("delete_data")

        #When Clicked, a pop-up will appear that will ask for confirmation.
        self.delete_data.clicked.connect(self.delete_content)

        self.about_us = QtWidgets.QPushButton(self.centralwidget)
        self.about_us.setEnabled(True)
        self.about_us.setGeometry(QtCore.QRect(60, 400, 301, 91))
        self.about_us.setObjectName("about_us")
        self.back_main = QtWidgets.QPushButton(self.centralwidget)
        self.back_main.setEnabled(True)
        self.back_main.setGeometry(QtCore.QRect(60, 530, 301, 91))
        self.back_main.setObjectName("back_main")

        #When Clicked, goes back to main
        self.back_main.clicked.connect(self.open_main)

        settings_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settings_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 26))
        self.menubar.setObjectName("menubar")
        settings_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(settings_2)
        self.statusbar.setObjectName("statusbar")
        settings_2.setStatusBar(self.statusbar)

        self.retranslateUi(settings_2)
        QtCore.QMetaObject.connectSlotsByName(settings_2)

    def retranslateUi(self, settings_2):
        _translate = QtCore.QCoreApplication.translate
        settings_2.setWindowTitle(_translate("settings_2", "Settings"))
        self.theme_chager.setText(_translate("settings_2", "Change Light and Dark Mode"))
        self.settings.setText(_translate("settings_2", "Settings"))
        self.delete_data.setText(_translate("settings_2", "Delete All Data"))
        self.about_us.setText(_translate("settings_2", "About Us"))
        self.back_main.setText(_translate("settings_2", "Back to Main"))

    #Edits the content of json file "theme"
    def edit_theme(self):
        #reads content of Theme
        with open("settings/theme.json", 'r') as f:
            json_object = json.load(f) 
            theme = json_object['theme']

            #if condition to see if theme is dark or light, and then converts it to its oppostie
            if theme == "light":
                json_object["theme"] = "dark"
            elif theme == "dark":
                json_object["theme"] = "light"
            
            # Write the updated data back to the JSON file
            with open("settings/theme.json", 'w') as f:
                json.dump(json_object, f)

    #Method to delete all profile data
    def delete_content(self):
        #open window delete content
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_confirm()
        self.ui.setupUi(self.window)
        self.window.show()
        #settings_2.hide()
        
    #Method to close settings and open main (BUGGED)
    def open_main(self):
        settings_2.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings_2 = QtWidgets.QMainWindow()
    ui = Ui_settings_2()
    ui.setupUi(settings_2)
    settings_2.show()
    sys.exit(app.exec_())