# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_routine.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

#Class that views routine of intensity and program
class Ui_view_routine(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(412, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 60, 431, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(170, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        self.main_label.setFont(font)
        self.main_label.setObjectName("main_label")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 60, 412, 561))
        self.listView.setObjectName("listView")

        self.list = QtGui.QStandardItemModel(self.listView)
        self.populate_list

        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 680, 421, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.proceed = QtWidgets.QPushButton(self.centralwidget)
        self.proceed.setGeometry(QtCore.QRect(200, 630, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.proceed.setFont(font)
        self.proceed.setObjectName("proceed")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(10, 650, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Create List Data by calling the populate_lsit method
        self.model = QtGui.QStandardItemModel(self.listView)  #Create the model
        self.populate_list()  #Populate the list

        #Views list
        self.listView.setModel(self.model) 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "View Routine"))
        self.main_label.setText(_translate("MainWindow", "Workout"))
        self.proceed.setText(_translate("MainWindow", "Let\'s Go!"))
        self.back_button.setText(_translate("MainWindow", "Back"))

    #Method to put workout within the list depending on the JSON file data per workout
    def populate_list(self):
        workouts = ["Item 1", "Item 2", "Item 3", "Item 4", "Item 5"]

        #Runs a for loop to then append item
        #FOr every item in workouts list, run the loop:
        for workout in workouts:
            workout = QtGui.QStandardItem(workout)
            self.model.appendRow(workout) #Appends workout data to the listview


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_view_routine()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
